KnapsackPro/knapsack_pro-ruby

- lib/knapsack_pro/adapters/base_adapter.rb
- lib/knapsack_pro/adapters/cucumber_adapter.rb
- lib/knapsack_pro/adapters/minitest_adapter.rb
- lib/knapsack_pro/adapters/rspec_adapter.rb
- spec/knapsack_pro/adapters/base_adapter_spec.rb
- spec/knapsack_pro/adapters/cucumber_adapter_spec.rb
- spec/knapsack_pro/adapters/minitest_adapter_spec.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
As proposed in the PR for the knapsack repo.
https://github.com/ArturT/knapsack/pull/27
> Change file path patterns to support 1-level symlinks by default

- lib/knapsack_pro/runners/minitest_runner.rb
Due to the changes in [this PR on Rake itself](https://github.com/ruby/rake/pull/97), executing the minitest rake task for Knapsack caused our test output to be filled with so many extraneous warning messages during test execution it both caused the output to be unreadably long and caused the semaphoreci threads to error out, apparently due to lack of memory. This reverts the setting for warnings on the Rake task defined in minitest_runner.rb to the pre-Rake v11.0.0 default, resolving both issues.
> Changed rake task in minitest_runner.rb to have no warnings output

- lib/knapsack_pro/report.rb
- spec/knapsack_pro/report_spec.rb
Related issue: https://github.com/KnapsackPro/knapsack_pro-ruby/issues/7
> Don't fail when there is no tests to run on a node

- CHANGELOG.md
- README.md
- lib/knapsack_pro/client/api/v1/build_distributions.rb
- lib/knapsack_pro/client/connection.rb
- lib/knapsack_pro/config/env.rb
- spec/fixtures/vcr_cassettes/api/v1/build_distributions/subset/success.yml
- spec/knapsack_pro/client/api/v1/build_distributions_spec.rb
- spec/knapsack_pro/client/connection_spec.rb
- spec/knapsack_pro/config/env_spec.rb
Related to issues:
https://github.com/KnapsackPro/knapsack_pro-ruby/issues/15
https://github.com/KnapsackPro/knapsack_pro-ruby/issues/12
> Use fixed test suite split by default

- lib/knapsack_pro/report.rb
- spec/knapsack_pro/report_spec.rb
Fix bug in queue mode with recording test files time execution data. Previously the same test files time execution data where multiple times send to Knapsack Pro API.
> Fix bug in queue mode with recording test files time execution data

- CHANGELOG.md
- README.md
- lib/knapsack_pro/adapters/base_adapter.rb
- lib/knapsack_pro/adapters/cucumber_adapter.rb
- lib/knapsack_pro/adapters/minitest_adapter.rb
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/adapters/spinach_adapter.rb
- lib/knapsack_pro/client/connection.rb
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/report.rb
- spec/knapsack_pro/adapters/base_adapter_spec.rb
- spec/knapsack_pro/adapters/cucumber_adapter_spec.rb
- spec/knapsack_pro/adapters/minitest_adapter_spec.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/adapters/spinach_adapter_spec.rb
- spec/knapsack_pro/client/connection_spec.rb
- spec/knapsack_pro/config/env_spec.rb
- spec/knapsack_pro/report_spec.rb
- spec/knapsack_pro_spec.rb
* Add supported for log levels `fatal` and `error` by `KNAPSACK_PRO_LOG_LEVEL` environment variable.
* Allow `KNAPSACK_PRO_LOG_LEVEL` case insensitive.
* Move all messages related to requests to Knapsack Pro API in log `debug` level and keep `info` level only for important messages like how to retry tests in development or info why something works this way or the other (for instance why tests were not executed on the CI node).
> Improvements in log levels and messages for debug and info levels

- CHANGELOG.md
- README.md
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/formatters/rspec_queue_formatter.rb
- lib/knapsack_pro/formatters/rspec_queue_summary_formatter.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/config/env_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
* Add RSpec queue formatter and show summary of failed and pending tests at the end of queue mode run. 
* Hide pending and failed tests for intermediate tests runs after each fetched test files from Knapsack Pro API. In order to do that we monkey patch default rspec formatters.
* Allow user to disable monkey patching for default rspec formatters with flag `KNAPSACK_PRO_MODIFY_DEFAULT_RSPEC_FORMATTERS`
Related to: https://github.com/rspec/rspec-core/issues/2416
> Add RSpec Queue Formatter to hide duplicated pending and failed tests in Queue Mode

- CHANGELOG.md
- lib/knapsack_pro/report.rb
- lib/knapsack_pro/tracker.rb
- lib/knapsack_pro/version.rb
- spec/knapsack_pro/tracker_spec.rb
Related to issue with: rspec-retry
https://github.com/KnapsackPro/knapsack_pro-ruby/issues/32
> Handle case when start timer was not called (rspec-retry issue)

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
This should fix Queue Mode for RSpec. This change is based on changes introduced in RSpec 3.6.0
https://github.com/rspec/rspec-core/pull/2379
* `RSpec.clear_examples` in rspec 3.6.0 clears examples __without__ shared examples. That's good because we want to have loaded shared examples between rspec runs.
* `RSpec.clear_examples` in rspec < 3.6.0 clears examples __and__ shared examples. That's bad because the tests fails because shared examples are not loaded.
`RSpec.clear_examples` does an additional thing which is cleared formatters and report. We don't want that because we want to accumulate info about failed/pending tests so we can show at the very end of Queue Mode output the info about summary of tests (what failed and what's pending).
Instead of using `RSpec.clear_examples` we do …
> Clear RSpec examples without shared examples in similar way as in RSpec 3.6.0

- CHANGELOG.md
- README.md
- lib/knapsack_pro/base_allocator_builder.rb
- lib/knapsack_pro/config/env.rb
- spec/knapsack_pro/base_allocator_builder_spec.rb
- spec/knapsack_pro/config/env_spec.rb
* Add KNAPSACK_PRO_TEST_DIR and support for it
* Run tests from multiple directories 
This is based on PR: https://github.com/ArturT/knapsack/pull/35
> Add ability to set test_dir using an environment variable

- CHANGELOG.md
- README.md
- lib/knapsack_pro/adapters/base_adapter.rb
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/hooks/queue.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/adapters/base_adapter_spec.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/hooks/queue_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
Add a way to defined before queue hook and after queue hook in Knapsack Pro Queue Mode.
```ruby
KnapsackPro::Hooks::Queue.before_queue do |queue_id|
end
KnapsackPro::Hooks::Queue.after_queue do |queue_id|
end
```
Context:
* The before queue hook is run in context of the `RSpec.before(:suite)` so you have access to whatever method RSpec provides.
* The after queue hook is run outside of `RSpec.after(:suite)` context due to the fact we know when the queue is ended only when all tests fetched from Knapsack Pro API are executed hence we are not able to define `RSpec.after(:suite)` before the last run of a subset of tests from the work queue because we don't know which subset will be the last one. 
Here is related PR with after subset queue hook: …
> Add before and after queue hooks

- CHANGELOG.md
- README.md
- lib/knapsack_pro.rb
- lib/knapsack_pro/railtie.rb
If you use Rails then knapsack_pro can autoload knapsack_pro rake tasks.
Thanks to that you don't need to modify Rakefile in your project.
Example how other gems load rake tasks:
https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed_job.rb#L20
https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag.rb#L124
Related change in docs: TODO
> Autoload knapsack_pro rake tasks with Rails Railties

- CHANGELOG.md
- lib/knapsack_pro/adapters/base_adapter.rb
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/formatters/rspec_queue_summary_formatter.rb
- lib/knapsack_pro/report.rb
- lib/knapsack_pro/tracker.rb
- spec/knapsack_pro/adapters/base_adapter_spec.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/report_spec.rb
- spec/knapsack_pro/tracker_spec.rb
This PR changes a few related things:
Example summary output from normal RSpec.
```
Finished in 0.01862 seconds (files took 0.11808 seconds to load)
23 examples, 3 failures, 2 pending
Failed examples:
rspec ./spec/features/calculator_spec.rb:7 # Calculator when try to add without provided numbers result is 0
rspec ./spec/bar_spec.rb:2 # Bar should equal false
rspec ./spec/foo_spec.rb:2 # Foo should equal false
```
This is what RSpec output will look like in Queue Mode thanks to this PR.
Note there is missing part `(files took 0.11808 seconds to load)`. It's on purpose because there is multiple intermediates reloads of test examples. We don't track the total load time in Queue Mode.
```
Finished in 0.01862 seconds
23 examples, 3 failures, 2 pending
Failed examples:
rspec …
```
> Add in Queue Mode the RSpec summary with info about examples, failures and pending tests

- CHANGELOG.md
- README.md
- lib/knapsack_pro/allocator.rb
- lib/knapsack_pro/client/connection.rb
- lib/knapsack_pro/queue_allocator.rb
- lib/knapsack_pro/report.rb
- lib/knapsack_pro/runners/queue/base_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/client/connection_spec.rb
- spec/knapsack_pro/queue_allocator_spec.rb
- spec/knapsack_pro/report_spec.rb
- spec/knapsack_pro/runners/queue/base_runner_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
* When Knapsack Pro API doesn't work then start executing tests based on directory names.
* Guarantee all test files are executed at least once across CI nodes.
> Fallback mode for Queue Mode when Knapsack Pro API doesn't work

- CHANGELOG.md
- knapsack_pro.gemspec
- lib/knapsack_pro/adapters/rspec_adapter.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
It improves how we track time for tests in RSpec.
This PR is based on fix: https://github.com/ArturT/knapsack/pull/64
> Update RSpec timing adapter to be more resilient

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
Use around :each so thanks to that we can track time for around :each defined by user in spec_helper or rails_helper
> Fix to record proper time for around(:each) in RSpec 

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
This way knapsack will handle exception and switch to fallback mode when there will be issue with API availability.
```
Errno::ETIMEDOUT: Failed to open TCP connection to api.knapsackpro.com:443 (Connection timed out - connect(2) for "api.knapsackpro.com" port 443)
/workspace/vendor/bundle/ruby/2.3.0/gems/knapsack_pro-0.54.0/lib/knapsack_pro/client/connection.rb:88:in `post'
/workspace/vendor/bundle/ruby/2.3.0/gems/knapsack_pro-0.54.0/lib/knapsack_pro/client/connection.rb:12:in `call'
/workspace/vendor/bundle/ruby/2.3.0/gems/knapsack_pro-0.54.0/lib/knapsack_pro/queue_allocator.rb:15:in `test_file_paths'
/workspace/vendor/bundle/ruby/2.3.0/gems/knapsack_pro-0.54.0/lib/knapsack_pro/runners/queue/base_runner.rb:21:in `test_file_paths' …
```
> Switch to fallback mode when failed to open TCP connection to API

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
- spec/knapsack_pro/client/connection_spec.rb
Only Knapsack Pro API response 2xx, 3xx, 4xx should be treated as successful. When API response is 5xx then we use Fallback Mode to run tests.
This should allow to run tests even in case of Knapsack Pro API 500 error.
Related: 
Issue: https://github.com/KnapsackPro/knapsack_pro-ruby/issues/68
First reported problem and PR: https://github.com/KnapsackPro/knapsack_pro-ruby/pull/67
> Run tests in Fallback Mode when API response is 5xx

- CHANGELOG.md
- lib/knapsack_pro/adapters/base_adapter.rb
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/runners/queue/minitest_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- lib/knapsack_pro/tracker.rb
- spec/knapsack_pro/adapters/base_adapter_spec.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/runners/queue/minitest_runner_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
This fix allows recording default timing 0.1s for test files like:
* test file is empty
* test file has only pending tests
* test file has a syntax error
* test file is empty
* test file has only pending tests
* test file has a syntax error (this breaks the runtime, the Knapsack Pro API will run the same set of tests when you retry failed CI node)
> Track time execution of all tests assigned to CI node in Queue Mode even when they did not run due syntax error or being pending/empty in test run

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
When a request fails 3 times with `Errno::EPIPE` then run tests in Fallback Mode.
> Run Fallback Mode for exception Errno::EPIPE

- CHANGELOG.md
- README.md
- lib/knapsack_pro/config/env.rb
- spec/fixtures/vcr_cassettes/api/v1/build_distributions/subset/invalid_test_suite_token.yml
- spec/fixtures/vcr_cassettes/api/v1/build_distributions/subset/success.yml
- spec/fixtures/vcr_cassettes/api/v1/build_subsets/create/invalid_test_suite_token.yml
- spec/fixtures/vcr_cassettes/api/v1/build_subsets/create/success.yml
- spec/integration/api/build_distributions_subset_spec.rb
- spec/integration/api/build_subsets_create_spec.rb
- spec/knapsack_pro/client/connection_spec.rb
- spec/knapsack_pro/config/env_spec.rb
This change is only for the maintainer of this repository.
`.dev` domain does not work anymore due Google acquired it. We should use `.test` domain.
https://medium.engineering/use-a-dev-domain-not-anymore-95219778e6fd
> Use .test domain for development mode

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
- spec/knapsack_pro/client/connection_spec.rb
When API returns 5xx error we don't retry the request. 
Because of that, we run tests in Fallback Mode right away when nginx returns 502 error when could not connect to unicorn process on API side.
Retry request 3 times. If all 3 requests fail then start Fallback Mode.
Thanks to this change during API traffic peak time the Fallback Mode will be started only when it actually needs to.
> Retry request 3 times when API returns 5xx HTTP status

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
When a request fails 3 times with `OpenSSL::SSL::SSLError` then run tests in Fallback Mode.
Error `OpenSSL::SSL::SSLError` can happen when certificate verify failed for Knapsack Pro API. It could happen during DNS propagation and changed SSL certificate for API.
> Run Fallback Mode when OpenSSL::SSL::SSLError certificate verify failed for API

- CHANGELOG.md
- lib/knapsack_pro/client/api/v1/queues.rb
- spec/knapsack_pro/client/api/v1/queues_spec.rb
Don’t send test_files for already initialized Queue. Thanks to that we reduce data transfer. This also makes requests much faster (even 10 times faster for test suite with 5000 test files).
> Reduce data transfer and speed up usage of Knapsack Pro API for Queue Mode

- CHANGELOG.md
- lib/knapsack_pro/report.rb
- lib/knapsack_pro/runners/queue/minitest_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/report_spec.rb
- spec/knapsack_pro/runners/queue/minitest_runner_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
Sometimes users have in their tests code that clears `tmp` directory. For instance, user can have RSpec hooks like `after(:each)` or `after(:suite)` that remove the content of `tmp` folder.
knapsack_pro gem uses `tmp/knapsack_pro/queue/` directory to store json files with a recorded time of tests. 
This pull request adds log error to notify the user when the `tmp/knapsack_pro/queue/` directory is empty even when some test files where executed. It means the user has probably RSpec hook or some other code that clears `tmp` directory which breaks knapsack_pro.
Another reason might be that you forgot to add `Knapsack::Adapters::RspecAdapter.bind` in your `rails_helper.rb` or `spec_helper.rb`. Please follow the installation guide again: https://docs.knapsackpro.com/integration/
> Logs error on lost info about recorded timing for test files due to missing json files in Queue Mode

- CHANGELOG.md
- lib/knapsack_pro/tracker.rb
- spec/knapsack_pro/tracker_spec.rb
When test file is pending, empty with no tests or has syntax error then we assume default time execution 0.1s for it. This helps to better allocate it in Queue Mode for future CI build runs.
It turned out that when the test file was executed then measured time was added to 0.1 seconds. 
Related to PR: https://github.com/KnapsackPro/knapsack_pro-ruby/pull/71
We should not add default 0.1s to measured test file time.
> Fix bug: default test file time should not be added to measured time

- CHANGELOG.md
- lib/knapsack_pro/report.rb
- lib/knapsack_pro/runners/queue/minitest_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/report_spec.rb
- spec/knapsack_pro/runners/queue/minitest_runner_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
Fix bug with not showing in logs info about measured time being lost due to:
* missing Knapsack::Adapters::RspecAdapter.bind
* cleared tmp directory
* all tests being empty, pending or have syntax error
Related: https://github.com/KnapsackPro/knapsack_pro-ruby/pull/83
> Fix log info when measured time of tests was lost

- CHANGELOG.md
- lib/knapsack_pro/config/ci/gitlab_ci.rb
- lib/knapsack_pro/config/env.rb
- spec/knapsack_pro/config/ci/gitlab_ci_spec.rb
- spec/knapsack_pro/config/env_spec.rb
* Use `CI_PIPELINE_ID` as build ID for GitLab CI because it is unique across parallel jobs
* Load GitLab CI envs first to avoid edge case with an order of loading envs for `CI_NODE_INDEX`. Gitlab CI starts from 1 instead of index 0 for `CI_NODE_INDEX`. We should first check if CI is Gitlab CI then do `CI_NODE_INDEX - 1`. Otherwise, assume it's other CI provider and just use `CI_NODE_INDEX`.
> Fix GitLab CI environment variables integration

- CHANGELOG.md
- README.md
- lib/knapsack_pro/config/ci/semaphore2.rb
- spec/knapsack_pro/config/ci/semaphore2_spec.rb
* `SEMAPHORE_JOB_COUNT` - total number of jobs generated via parallelism property
* `SEMAPHORE_JOB_INDEX` - value in the range from 1 to `SEMAPHORE_JOB_COUNT` which represents the index of a particular job in the list of generated jobs.
https://docs.semaphoreci.com/article/50-pipeline-yaml#parallelism
> Add support for job index and job count for parallelism in Semaphore 2.0

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/rspec_runner.rb
Call `RSpec.configuration.reset_filters` for RSpec only if this method exists. This way we won't call it for old RSpec version like RSpec 3.1.0
> Allow to use Queue Mode for old RSpec versions that don't have RSpec.configuration.reset_filters method

- CHANGELOG.md
- README.md
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/runners/queue/cucumber_runner.rb
- spec/knapsack_pro/config/env_spec.rb
This solves issue https://github.com/KnapsackPro/knapsack_pro-ruby/issues/97
```bash
KNAPSACK_PRO_CUCUMBER_QUEUE_PREFIX='bundle exec spring'
or
KNAPSACK_PRO_CUCUMBER_QUEUE_PREFIX='bin/spring'
```
It would add this prefix to Cucumber command to run it faster in Knapsack Pro Queue Mode thanks to spring gem.
> Add KNAPSACK_PRO_CUCUMBER_QUEUE_PREFIX to allow run Cucumber with spring gem in Queue Mode

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
- spec/knapsack_pro/client/connection_spec.rb
Increase delay between request retry to Knapsack Pro API:
* from 2s to 4s for 2nd request 
* from 4s to 8s for 3rd request
This should help with not flooding Knapsack Pro API with too fast request retries.
> Increase delay between request retry to Knapsack Pro API 

- CHANGELOG.md
- README.md
- lib/knapsack_pro/allocator.rb
- lib/knapsack_pro/config/ci/base.rb
- lib/knapsack_pro/config/ci/buildkite.rb
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/queue_allocator.rb
- spec/knapsack_pro/allocator_spec.rb
- spec/knapsack_pro/config/ci/base_spec.rb
- spec/knapsack_pro/config/ci/buildkite_spec.rb
- spec/knapsack_pro/config/env_spec.rb
- spec/knapsack_pro/queue_allocator_spec.rb
You run tests in Queue Mode with flag `KNAPSACK_PRO_FIXED_TEST_SUITE_SPLIT=true` or Regular Mode with the flag `KNAPSACK_PRO_FIXED_TEST_SUITE_SPLIT=true` (default).
How to reproduce race condition:
* You run 1st CI build and one of parallel CI nodes tests failed.
* You retry failed CI node. We expect knapsack_pro will run the same set of tests on the CI node during retry as it was recorded for the first CI node run. Let's assume knapsack_pro could not connect to Knapsack Pro API. In such a case, the Fallback Mode is started and a different set of tests are run on the CI node. This can lead to false-positive because different tests can be green and the retried CI node did not run failing tests at all.
knapsack_pro should not allow running tests in Fallback Mode in the case when CI node was …
> Do not allow Fallback Mode when the CI node was retried to avoid running the wrong set of tests

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/cucumber_runner.rb
This is a small improvement to don't assume when tests failed then the exit status is always 1. It can be something else so it's good to pass non zero exit status from Cucumber to knapsack_pro in Queue Mode.
> Pass non zero exit status from Cucumber as exit status for Cucumber executed in Queue Mode

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
This PR fixes a bug that could lead to running multiple times `before_queue` hook.
If `KnapsackPro::Hooks::Queue.before_queue` hook has block of code that raises an exception then ensure the hook was called only once.
> If KnapsackPro::Hooks::Queue.before_queue hook has block of code that raises an exception then ensure the hook was called only once

- lib/knapsack_pro/report.rb
- spec/knapsack_pro/report_spec.rb
Hey, I noticed this small typo when debugging an issue locally.
> Fix typo `testes` -> `tests`

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/cucumber_runner.rb
- spec/knapsack_pro/runners/queue/cucumber_runner_spec.rb
Sometimes Cucumber in Queue Mode could be killed by CI server for some reason (like exceeding the memory).
We want to make sure the user gets meaningful error as to what happened (and be double sure that killing the process never results in a false positive).
We raise exception when Cucumber process in Queue Mode failed to execute properly (never exited on its own).
> Raise error from Cucumber Queue Mode runner when system process doesn't finish execution

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
- spec/knapsack_pro/client/connection_spec.rb
* Increase request retry timebox from 4s to 8s to not flood Knapsack Pro API with too many requests in a short period of time and to give time for API server to autoscale and add additional machines to serve traffic
This is the default behavior of knapsack_pro to start running tests in Fallback Mode when 3 times request to API fails.
8+16 = 24s wait time - knapsack_pro will try to connect with API within 24s before starting running tests in Fallback Mode
* When Fallback Mode is disabled with env `KNAPSACK_PRO_FALLBACK_MODE_ENABLED=false` then retry the request to Knapsack Pro API for 6 times instead of only 3 times.
Here is related info when some users want to disable Fallback Mode: https://github.com/KnapsackPro/knapsack_pro-ruby#required-ci-configuration-if-you-use-retry-single-failed-ci …
> Increase request retry timebox from 4s to 8s and when Fallback Mode is disabled then retry request 6 times

- CHANGELOG.md
- lib/knapsack_pro/slow_test_file_determiner.rb
- lib/knapsack_pro/test_case_detectors/rspec_test_example_detector.rb
- spec/knapsack_pro/slow_test_file_determiner_spec.rb
- spec/knapsack_pro/test_case_detectors/rspec_test_example_detector_spec.rb
Fix for an auto split of slow RSpec test files by test examples when using `KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true` and `parallel_tests` gem. Save the JSON reports with unique file names with the CI node index in the name to avoid accidentally overriding the files on the same disk.
> Fix for an auto split of slow RSpec test files by test examples when using parallel_tests gem

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
- spec/knapsack_pro/client/connection_spec.rb
This adds log warning message: `Next request in 8s...` etc to knapsack pro logger to notify the user when next retry request to Knapsack Pro API will happen.
CodeShip seems to freeze when no output for a long time so we print some output to show that knapsack_pro process is working.
```
4 #50431]  WARN -- : [knapsack_pro] #<SocketError: Failed to open TCP connection to api-fake.knapsackpro.test:3000 (getaddrinfo: nodename nor servname provided, or not known)>
W, [2020-06-02T09:28:04.961195 #50431]  WARN -- : [knapsack_pro] Wait 8s and retry request to Knapsack Pro API.
W, [2020-06-02T09:28:04.961239 #50431]  WARN -- : [knapsack_pro] Next request in 8s...
W, [2020-06-02T09:28:06.961402 #50431]  WARN -- : [knapsack_pro] Next request in 6s...
W, [2020-06-02T09:28:08.966389 #50431]  WARN -- : …
```
> Log when next retry request to Knapsack Pro API happens before starting Fallback Mode

- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
Passing formatting params to rspec without delimiter results in redundantly added `progress` formatter.
Check for rspec params prefix instead of inclusion check.
> Support for non-delimited formatting params of rspec

- CHANGELOG.md
- README.md
- lib/knapsack_pro/config/ci/github_actions.rb
- spec/knapsack_pro/config/ci/github_actions_spec.rb
This PR adds support for CI build ID for Github Actions. 
* Thanks to that you can run concurrent CI builds for the same commit & branch in Knapsack Pro Queue Mode.
* Parallel jobs that started work after Queue was already consumed won't initialize a new Queue (thanks to that you won't accidentally run tests twice).
List of [env variables in Github Actions](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables).
`GITHUB_RUN_ID` - A unique number for each run within a repository. __This number does not change if you re-run the workflow run.__
When you retry parallel jobs in Github Actions then `GITHUB_RUN_ID` stays the same. Because of this in Knapsack Pro Queue Mode the Knapsack Pro API will assume the queue was …
> Add support for CI build ID for Github Actions

- CHANGELOG.md
- README.md
- lib/knapsack_pro/base_allocator_builder.rb
- lib/knapsack_pro/config/env.rb
- spec/knapsack_pro/config/env_spec.rb
When you use RSpec split by test examples 
```
KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
```
https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it
and you saw error like:
```
Don't know how to build task 'knapsack_pro:rspec_test_example_detector' (See the list of available tasks with `rake --tasks`)
```
knapsack_pro by default adds prefix `bundle exec` before the rake task (knapsack_pro:rspec_test_example_detector).
You can try run it without `bundle exec` prefix.
Set `KNAPSACK_PRO_RSPEC_TEST_EXAMPLE_DETECTOR_PREFIX=""` to empty string to remove default prefix `bundle exec`. This should help run the task task properly.
> Add KNAPSACK_PRO_RSPEC_TEST_EXAMPLE_DETECTOR_PREFIX to customize prefix for generating test examples report when using RSpec split by test examples

- CHANGELOG.md
- lib/knapsack_pro/adapters/cucumber_adapter.rb
- lib/knapsack_pro/adapters/minitest_adapter.rb
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/adapters/test_unit_adapter.rb
- lib/knapsack_pro/base_allocator_builder.rb
- lib/knapsack_pro/formatters/rspec_json_formatter.rb
- lib/knapsack_pro/formatters/rspec_queue_profile_formatter_extension.rb
- lib/knapsack_pro/formatters/rspec_queue_summary_formatter.rb
- lib/knapsack_pro/runners/cucumber_runner.rb
- lib/knapsack_pro/runners/queue/minitest_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- lib/knapsack_pro/runners/rspec_runner.rb
- lib/knapsack_pro/runners/test_unit_runner.rb
- lib/knapsack_pro/test_case_detectors/rspec_test_example_detector.rb
Explicitly call root test runner class to avoid a confusing error when test runner gem is not loaded 
These changes will help us see more explicit and clear errors when test runner gem like RSpec is not loaded properly.
For instance, it could help avoid misunderstanding of error like https://github.com/KnapsackPro/knapsack_pro-ruby/issues/119
* Use ::RSpec instead of RSpec to be more explicit about using gem RSpec
* Use ::Cucumber instead of Cucumber
* Use ::Minitest instead of Minitest
* Use ::Test::Unit instead of Test::Unit
* Use ::Turnip instead of Turnip
> Explicitly call root test runner class to avoid a confusing error when test runner gem is not loaded 

- CHANGELOG.md
- README.md
- lib/knapsack_pro/hooks/queue.rb
- spec/knapsack_pro/hooks/queue_spec.rb
Allow defining multiple times hooks for Queue Mode like 
* `KnapsackPro::Hooks::Queue.before_queue`
* `KnapsackPro::Hooks::Queue.after_subset_queue`
* `KnapsackPro::Hooks::Queue.after_queue`
So far you could define only once a hook for Queue Mode.  This might be less convenient when you would like to keep hooks related code in a few separate files. 
You can now define multiple times the same hook. Example:
```ruby
KnapsackPro::Hooks::Queue.before_queue do
puts '1st call'
end
KnapsackPro::Hooks::Queue.before_queue do
puts '2nd call'
end
```
This works similarly to hooks in RSpec so you can define them many times.
Here are examples of using all hooks in Queue Mode:
https://github.com/KnapsackPro/knapsack_pro-ruby#what-hooks-are-supported-in-queue-mode
> Allow defining Queue Mode hooks multiple times (before_queue, after_subset_queue, after_queue)

- CHANGELOG.md
- lib/knapsack_pro/adapters/test_unit_adapter.rb
- spec/knapsack_pro/adapters/test_unit_adapter_spec.rb
When you use test runner `test-unit` https://test-unit.github.io and your test file has shared examples (`share_should` method) and regular test cases then when tests are executed in random order for this file then it could lead to knapsack_pro detecting wrong test file path for executed test if first test case is shared example for a test file.
Bug also happens when test file contains only shared examples.
Example test file with shared examples https://github.com/KnapsackPro/rails-app-with-knapsack_pro/blob/383cb917755f6d34bd3cacd8261226cc769e49a1/test-unit/models/shared_should_test.rb#L33
Root problem is that detecting test file path based on shared examples method returns wrong test file path.
```ruby
module KnapsackPro
module Adapters
class TestUnitAdapter < BaseAdapter …
```
> Improve detection of test file path in test-unit runner for test files with shared examples

- CHANGELOG.md
- README.md
- lib/knapsack_pro/client/connection.rb
- lib/knapsack_pro/config/env.rb
- spec/knapsack_pro/client/connection_spec.rb
- spec/knapsack_pro/config/env_spec.rb
Before this PR the knapsack_pro gem does 3 attempts to connect to Knapsack Pro API before starting running tests in [Fallback Mode](https://github.com/KnapsackPro/knapsack_pro-ruby#what-happens-when-knapsack-pro-api-is-not-availablenot-reachable-temporarily).
The described problem below is relevant only for running knapsack_pro in Regular Mode.
Assume:
* there are 2 parallel CI nodes. 
* the user uses knapsack_pro gem in Regular Mode.
Here you can learn about the [difference between Regular Mode and Queue Mode](https://docs.knapsackpro.com/2020/how-to-speed-up-ruby-and-javascript-tests-with-ci-parallelisation)
* CI node index 0 can't connect to the API so it starts running tests in Fallback Mode.
* CI node index 1 can't connect to the API so it starts running tests in Fallback Mode.
The …
> When you use Regular Mode then try 6 attempts to connect to the API instead of 3 attempts

- CHANGELOG.md
- lib/knapsack_pro/crypto/branch_encryptor.rb
Add new branch names like main, development etc. There is no need to encrypt them. Thanks to that Knapsack Pro API can use them as default branches to get from them recorded tests timing data that could be used for a fresh new branch CI build.
Add branches with prefix refs/heads/ that are used on Github Actions.
> Update list of non encryptable branches

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
- spec/knapsack_pro/client/connection_spec.rb
* Improve logger to show failed requests URL
* More clear message when showing info about waiting for next request retry
Example output:
```
W, [2020-09-23T13:04:03.675239 #52494]  WARN -- : [knapsack_pro] POST http://api-fake.knapsackpro.test:3000/v1/queues/queue
W, [2020-09-23T13:04:03.675327 #52494]  WARN -- : [knapsack_pro] Request failed due to:
W, [2020-09-23T13:04:03.675354 #52494]  WARN -- : [knapsack_pro] #<SocketError: Failed to open TCP connection to api-fake.knapsackpro.test:3000 (getaddrinfo: nodename nor servname provided, or not known)>
W, [2020-09-23T13:04:03.675392 #52494]  WARN -- : [knapsack_pro] Wait for 8s before retrying the request to Knapsack Pro API.
W, [2020-09-23T13:04:05.678955 #52494]  WARN -- : [knapsack_pro] 6s left before retry...
W, …
```
> Improve logger to show failed requests URL and when retry will happen

- CHANGELOG.md
- lib/knapsack_pro/test_case_detectors/rspec_test_example_detector.rb
- spec/knapsack_pro/test_case_detectors/rspec_test_example_detector_spec.rb
* Show actionable error - show how to reproduce RSpec dry-run command in development to check what's root problem of the RSpec failure
> More actionable error message when RSpec split by examples is not working due to RSpec dry-run failure

- CHANGELOG.md
- lib/knapsack_pro/tracker.rb
Using any variation of `Time.now` is not a reliable way of measuring elapsed time. It may be affected by jumps in the local clock.
Instead, we can use a more reliable `Process.clock_gettime(Process:: CLOCK_MONOTONIC)`.
For a detailed explanation, please read this blog post: https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/
https://github.com/ArturT/knapsack/pull/100
> Use Process.clock_gettime to measure track execution time

- CHANGELOG.md
- lib/knapsack_pro/base_allocator_builder.rb
- lib/knapsack_pro/client/api/v1/queues.rb
- lib/knapsack_pro/client/connection.rb
- lib/knapsack_pro/queue_allocator.rb
- lib/knapsack_pro/queue_allocator_builder.rb
- spec/knapsack_pro/client/api/v1/queues_spec.rb
- spec/knapsack_pro/queue_allocator_builder_spec.rb
- spec/knapsack_pro/queue_allocator_spec.rb
The very first request to Queue API is slow due to sending a list of test files from the disk. The bigger the test files list the slower is request. For a few thousand test files it can take 1+ second.
When a lot of requests from parallel CI nodes starting at the same time hit the Knapsack Pro API this can lead to slower performance of the API because requests with a list of test files can be slow. This leads to compound effect and degradation of API performance for very large projects using ~100+ parallel CI nodes.
When you use [RSpec split by test examples feature](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it) then each parallel CI node must generate a JSON report with test example ids in order to prepare a list of test files …
> Add support for an attempt to connect to existing Queue on API side to reduce slow requests number

- CHANGELOG.md
- lib/knapsack_pro/base_allocator_builder.rb
- lib/knapsack_pro/queue_allocator.rb
- lib/knapsack_pro/queue_allocator_builder.rb
- spec/knapsack_pro/queue_allocator_builder_spec.rb
- spec/knapsack_pro/queue_allocator_spec.rb
remove lazy loading of test files from disk and lazy generating of RSpec split by examples JSON report because the JSON report is needed on all parallel CI nodes to run tests properly when you use [RSpec split by test examples feature](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it).
The bug was revealed in this CI build
https://app.circleci.com/pipelines/github/KnapsackPro/rails-app-with-knapsack_pro/83/workflows/ccfc0b61-65ca-4e8f-87d5-4e2f0ebcda90/jobs/1377/parallel-runs/0?filterBy=ALL
When CI node did not generate JSON report with test example ids for slow test files (because it connected to existing Queue on API side) then you can't run tests. 
```
Failures:
1) Example of slow shared examples 
Failure/Error: raise 'Report …
```
> Fix RSpec split by test examples feature broken by lazy generating of JSON report with test example ids

- CHANGELOG.md
- lib/knapsack_pro/adapters/base_adapter.rb
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/report.rb
- lib/knapsack_pro/runners/cucumber_runner.rb
- lib/knapsack_pro/runners/minitest_runner.rb
- lib/knapsack_pro/runners/queue/cucumber_runner.rb
- lib/knapsack_pro/runners/queue/minitest_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- lib/knapsack_pro/runners/rspec_runner.rb
- lib/knapsack_pro/runners/spinach_runner.rb
- lib/knapsack_pro/runners/test_unit_runner.rb
- lib/knapsack_pro/slow_test_file_determiner.rb
- lib/knapsack_pro/test_case_detectors/rspec_test_example_detector.rb
- spec/knapsack_pro/adapters/base_adapter_spec.rb
- spec/knapsack_pro/runners/cucumber_runner_spec.rb
- spec/knapsack_pro/runners/minitest_runner_spec.rb
- spec/knapsack_pro/runners/queue/cucumber_runner_spec.rb
- spec/knapsack_pro/runners/queue/minitest_runner_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
- spec/knapsack_pro/runners/rspec_runner_spec.rb
- spec/knapsack_pro/runners/spinach_runner_spec.rb
- spec/knapsack_pro/runners/test_unit_runner_spec.rb
* Thanks to this we can automatically detect not properly configured project setup when someone forgot to add bind method like `KnapsackPro::Adapters::RSpecAdapter.bind`.
* Ensure `tmp/knapsack_pro` directory is not removed accidentally
> Verify test runner adapter bind method is called to track test files time execution and ensure tmp/knapsack_pro directory is not removed accidentally

- CHANGELOG.md
- README.md
- lib/knapsack_pro/tracker.rb
There is no need to keep this workaround with a fake default test file execution time 0.1s for test files that were not executed on CI because API already allows saving test files with 0 seconds.
https://github.com/KnapsackPro/knapsack_pro-ruby/pull/71
> Use 0 seconds as a default test file time execution instead of 0.1s because Knapsack Pro API already accepts 0 seconds value

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/tracker.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/tracker_spec.rb
This improves tracking test execution time. Especially for individual test examples in RSpec when you use [split by test examples feature](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it).
Previously sometimes individual test examples had 0 seconds of recorded time execution in the Knapsack Pro user dashboard.
This bug was introduced in [PR](https://github.com/KnapsackPro/knapsack_pro-ruby/pull/143).
> Improve test time execution tracking for RSpec

- .circleci/config.yml
- CHANGELOG.md
- knapsack_pro.gemspec
- lib/knapsack_pro/config/ci/circle.rb
- lib/knapsack_pro/repository_adapters/git_adapter.rb
- lib/knapsack_pro/runners/base_runner.rb
- lib/knapsack_pro/runners/queue/base_runner.rb
- lib/knapsack_pro/runners/queue/cucumber_runner.rb
- lib/knapsack_pro/runners/spinach_runner.rb
- lib/knapsack_pro/runners/test_unit_runner.rb
- spec/knapsack_pro/adapters/test_unit_adapter_spec.rb
- spec/knapsack_pro/config/ci/circle_spec.rb
- spec/knapsack_pro/repository_adapters/git_adapter_spec.rb
- spec/knapsack_pro/runners/queue/cucumber_runner_spec.rb
- spec/knapsack_pro/runners/spinach_runner_spec.rb
- spec/knapsack_pro/runners/test_unit_runner_spec.rb
- spec/spec_helper.rb
* adjust test suite to work with Ruby 3
* update development dependencies
* remove deprecated codeclimate gem
* add support for CirleCI `CIRCLE_WORKING_DIRECTORY` env var 
* remove support for detecting project dir for CircleCI 1.0 because it's not longer supported
```
Starting Mar 15, 2019:
All projects will require a CircleCI 2.0 configuration.
CircleCI 1.0 jobs will be viewable but will no longer run.
https://circleci.com/sunset1-0/eol-policy/
```
* add support for project directory with `~` in path
If you clone this project in development please remove your local copy of `Gemfile.lock` (it is ignored in `.gitignore`) and then run:
* rvm get stable
* rvm install ruby-3.0.1
* bundle install # this will generate a new `Gemfile.lock` with the latest gems as listed in …
> Use Ruby 3 in development and add small improvements

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- lib/knapsack_pro/runners/rspec_runner.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
- spec/knapsack_pro/runners/rspec_runner_spec.rb
Why don't allow to use RSpec tag option with [RSpec split by test examples feature](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it)?
https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it#warning-dont-use-rspec-tag-option
If you do it and you use at the same time `KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true` then `--tag` option might not be respected by RSpec due to [a bug in the RSpec](https://github.com/rspec/rspec-core/issues/2522). RSpec has a higher priority to run test examples like `spec/a_spec.rb[1:1]` than respect the `--tag` option. This can result in running test cases that you didn't intend to run.
We raise an exception when the user uses RSpec tag option at the …
> Do not allow to use the RSpec tag option together with the RSpec split by test examples feature in knapsack_pro gem in Regular Mode

- CHANGELOG.md
- lib/knapsack_pro/base_allocator_builder.rb
https://github.com/KnapsackPro/knapsack_pro-ruby/issues/150
I decided to use `require 'rspec/core/version'` instead of `Gem.loaded_specs["rspec-core"].version` because `require` would give us a more explicit error when RSpec gem can't be loaded (for instance it is not present in proper Gemfile group).
> Ensure RSpec is loaded to check its version for RSpec split by test examples feature

- CHANGELOG.md
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/runners/cucumber_runner.rb
- lib/knapsack_pro/runners/minitest_runner.rb
- lib/knapsack_pro/runners/queue/cucumber_runner.rb
- lib/knapsack_pro/runners/queue/minitest_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- lib/knapsack_pro/runners/rspec_runner.rb
- lib/knapsack_pro/runners/spinach_runner.rb
- lib/knapsack_pro/runners/test_unit_runner.rb
- lib/knapsack_pro/tracker.rb
- spec/knapsack_pro/config/env_spec.rb
- spec/knapsack_pro/runners/cucumber_runner_spec.rb
- spec/knapsack_pro/runners/queue/cucumber_runner_spec.rb
- spec/knapsack_pro/runners/queue/minitest_runner_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
- spec/knapsack_pro/runners/rspec_runner_spec.rb
- spec/knapsack_pro/runners/spinach_runner_spec.rb
- spec/knapsack_pro/tracker_spec.rb
* When you use Regular Mode and RSpec and you run first CI build then Knapsack Pro API returns a list of test files assigned to the CI node. If the test files have a pending test file then RSpec won't run it. This causes not measuring time execution for the pending test file. Because of that list of test files that is saved to Knapsack Pro API does not contain the pending test file.
* Problem happens when you retry CI node and you expect the same set of test files will be assigned to the CI node. But there is missing pending spec file which was not recorded during the first CI build run.
Track all test files assigned to the CI node and save them to Knapsack Pro API after tests are executed. Thanks to that pending test file will have default 0 seconds time execution. When you retry CI node …
> Track all test files assigned to a CI node in Regular Mode including pending test files in order to retry proper set of tests on the retried CI node

- spec/knapsack_pro/runners/minitest_runner_spec.rb
- spec/knapsack_pro/runners/test_unit_runner_spec.rb
Failing CI build: https://app.circleci.com/pipelines/github/KnapsackPro/knapsack_pro-ruby/461/workflows/4d56022a-5b83-4f29-968f-d9e90c48b91e/jobs/1450
Error:
```
Failures:
1) KnapsackPro::Runners::MinitestRunner.run when test files were returned by Knapsack Pro API runs tests
Failure/Error:
File.open(prerun_tests_report_path, 'w+') do |f|
f.write(report_json)
end
Errno::ENOENT:
No such file or directory @ rb_sysopen - tmp/knapsack_pro/tracker/prerun_tests_MinitestAdapter_node_0.json
```
> Add mocking to fix randomly failing spec

- CHANGELOG.md
- knapsack_pro.gemspec
- lib/knapsack_pro/adapters/rspec_adapter.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
* Use RSpec `example` from RSpec `each` hook instead of global `RSpec.current_example`. It allows running tests with async-rspec gem.
* breaking change: drop support for RSpec 2.x. It was already accidentally dropped due to added `context` RSpec hooks.
This PR is based on changes from knapsack gem:
https://github.com/KnapsackPro/knapsack/pull/117
> Use RSpec `example` block argument instead of the global `RSpec.current_example`. This allows to run tests with the `async-rspec` gem.

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/rspec_runner.rb
Related Issue: https://github.com/KnapsackPro/knapsack_pro-ruby/issues/159
> Rephrase log outputs in the Queue Mode RSpec runner

- CHANGELOG.md
- lib/knapsack_pro/slow_test_file_determiner.rb
- spec/knapsack_pro/slow_test_file_determiner_spec.rb
The bug is related to feature: [RSpec split by examples](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it).
When API https://docs.knapsackpro.com/api/v1/#build_distributions_last_get returns build distribution with all test files having time execution 0 seconds then all test files were detected as slow test files in knapsack_pro gem. This leads to loading a lot of test examples in RSpec. RSpec could take a lot of memory and slow down, freeze the CI server for the larger test suite.
When test files have no recorded time execution (time execution is 0 seconds) then they should not be detected as slow test files by [RSpec split by examples feature](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples- …
> Fix bug when test files have no recorded time execution then they should not be detected as slow test files for RSpec split by test examples feature

- lib/knapsack_pro/adapters/rspec_adapter.rb
Due to the way the adapter name is inferred in `KnapsackPro::Adapters::BaseAdapter`, `RspecAdapter#bind` will not write the bind file to the correct location and the command will fail. 
This adds an error message when `RspecAdapter#bind` is called, rather than silently inheriting the method from `RSpecAdapter`.
> add error message to RspecAdapter#bind

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
Raise exception only when RSpec inclusion rule includes `:focus` tag.
When tests can be skipped by RSpec?
The problem occurs when at least one of the test files has `:focus` tag. And when you use 
```ruby
RSpec.configure do |c|
c.filter_run_when_matching :focus
end
```
For instance, if a test file has content like this:
```ruby
describe ArticlesController, :focus do
it '1' do
expect(true).to be true
end
fit '2' do
expect(true).to be true
end
end
```
Then this sets RSpec filter to `focus: true`. You can see in RSpec output this: `Run options: include {:focus=>true}`
and as a result we can see in the RSpec output: `All examples were filtered out` so tests without the tag are skipped.
All further test files fetched from Queue are going to be skipped due to this filter `:focus => true`.
Using …
> Raise exception when using `:focus` tag to avoid skipping RSpec tests

- CHANGELOG.md
- lib/knapsack_pro/test_case_detectors/rspec_test_example_detector.rb
- spec/knapsack_pro/test_case_detectors/rspec_test_example_detector_spec.rb
Show a JSON report file content when RSpec fails during a dry run. The JSON report may contain the error message while RSpec does not produce any error to stdout/stderr. Let's show the JSON report content to make debugging easier.
This PR is an improvement for the [RSpec split by test examples feature](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it).
Thanks to that you can easily debug and find out what's the root issue of the RSpec failure during the dry run on your CI environment.
https://github.com/KnapsackPro/knapsack_pro-ruby/issues/170
More context in:
https://github.com/KnapsackPro/knapsack_pro-ruby/issues/170#issuecomment-1178140729
How to verify this PR actually helps.
We use …
> Show a JSON report file content when RSpec fails during a dry run

- README.md
* Improve language in the text about encryption
* Fix not working command examples (add missing " characters)
* Remove not accurate documentation. Encryption feature does not work with the RSpec split by examples feature
> Readme improvements for encryption feature

- CHANGELOG.md
- lib/tasks/encrypted_test_file_names.rake
[RSpec split by test examples](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it) feature can't be used at the same time when [encryption is enabled](https://github.com/KnapsackPro/knapsack_pro-ruby#test-file-names-encryption). 
Let's remove a preview of test examples from the rake task (`KNAPSACK_PRO_SALT=xxx bundle exec rake "knapsack_pro:encrypted_test_file_names[rspec]"`). It's not needed.
Related changes in the documentation: https://github.com/KnapsackPro/knapsack_pro-ruby/pull/176/files
Related old commit that we undo https://github.com/KnapsackPro/knapsack_pro-ruby/commit/96ec95d6c697a8b8753583615fca5a5a0416162c
There are technical limitations that prevented us from using the RSpec split by test examples feature at the same …
> Remove preview for encrypted RSpec test examples

- CHANGELOG.md
- lib/knapsack_pro/runners/rspec_runner.rb
When you run Knapsack Pro for RSpec in Regular Mode, and you enable [RSpec split by test examples](https://knapsackpro.com/faq/question/how-to-split-slow-rspec-test-files-by-test-examples-by-individual-it) feature, and you forget to set `RAILS_ENV=test` then`RSpec::Core::Parser` is not loaded.
```
... other envs
export KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true
bundle exec rake "knapsack_pro:rspec[--format d]"
```
It crashes with:
```
rake aborted!
NameError: uninitialized constant RSpec::Core::Parser
::RSpec::Core::Parser.parse(cli_args)
```
https://github.com/KnapsackPro/knapsack_pro-ruby/issues/180
Require `rspec/core` when running in Regular Mode. Thanks to that you don't need to remember to explicitly set `RAILS_ENV=test`.
It's easier to [try Knapsack Pro in development …
> Fix: Load `rspec/core` in Regular Mode when using RSpec split by test examples feature

- CHANGELOG.md
- lib/knapsack_pro/hooks/queue.rb
- lib/knapsack_pro/runners/queue/cucumber_runner.rb
- lib/knapsack_pro/runners/queue/minitest_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/hooks/queue_spec.rb
- spec/knapsack_pro/runners/queue/cucumber_runner_spec.rb
- spec/knapsack_pro/runners/queue/minitest_runner_spec.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
Currently there is only `after_subset_queue` hook and only works when subset finished. Adding a before subset hook to provide an ability to access to the subset queue to preserve some information beforehand which might be loss while CI node terminated in the middle of processing.
> Add before_subset_queue hook in queue mode

- CHANGELOG.md
- lib/knapsack_pro/allocator.rb
- lib/knapsack_pro/client/api/v1/build_distributions.rb
- lib/knapsack_pro/queue_allocator.rb
- spec/fixtures/vcr_cassettes/api/v1/build_distributions/subset/invalid_test_suite_token.yml
- spec/fixtures/vcr_cassettes/api/v1/build_distributions/subset/success.yml
- spec/integration/api/build_distributions_subset_spec.rb
- spec/knapsack_pro/allocator_spec.rb
- spec/knapsack_pro/client/api/v1/build_distributions_spec.rb
- spec/knapsack_pro/queue_allocator_spec.rb
Add an attempt to read from the cache for Regular Mode API.
This way, we can read the test suite split from the cache, and there is no need to send `test_files` in the request payload from the knapsack_pro gem for all parallel CI nodes.
This allows using Regular Mode with a large test suite (many thousands of test files across hundreds of parallel CI nodes) because requests from parallel CI nodes are fast. There is a limited number of slow requests with a big list of test files in the request payload.
* https://github.com/KnapsackPro/rails-app-with-knapsack_pro/pull/43
* https://github.com/KnapsackPro/docs.knapsackpro.com/pull/94
This PR is inspired by the improvement made for Queue Mode:
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/133
* follow up improvement …
> Add an attempt to read from the cache for Regular Mode API

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/tracker.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/tracker_spec.rb
Prevent the timer being stopped in the same test file.
Shout-out to @evanlok for the inspiration and code example
> Adjust the timer behaviour in the RSpec adapter

- spec/knapsack_pro/tracker_spec.rb
You could reproduce it with:
```
rspec --seed 4497 spec/knapsack_pro/tracker_spec.rb
```
OR
```
rspec --seed 4497 spec/knapsack_pro/tracker_spec.rb:101
```
OR 
you could keep running the test file a few times till you see an error. The flaky tests failed with the following error:
```
➜  knapsack_pro-ruby git:(master) rspec spec/knapsack_pro/tracker_spec.rb:101
Run options: include {:locations=>{"./spec/knapsack_pro/tracker_spec.rb"=>[101]}}
Randomized with seed 64227
KnapsackPro::Tracker
track time execution
when start timer was not called (rspec-retry issue)
is expected to eq 0
2nd spec (b_spec.rb) should have recorded time execution - because start_time was set during first call of stop_timer for the first spec (a_spec.rb) (FAILED - 1)
is expected to eql 2
is expected to equal true
is …
```
> Fix a flaky test for a tracker

- CHANGELOG.md
- lib/knapsack_pro/runners/rspec_runner.rb
- spec/knapsack_pro/runners/rspec_runner_spec.rb
In Regular Mode, we use RSpec::Core::RakeTask. By default, it prints an RSpec command with all test files and options provided to it. For a big test suite, this can be a large output.
We can suppress that with a verbose false option for the rake task only when [the log level is >= `warn`](https://docs.knapsackpro.com/ruby/reference/#knapsack_pro_log_level). 
* https://github.com/KnapsackPro/knapsack_pro-ruby/issues/189
https://stackoverflow.com/a/26299828/905697
> Suppress all RSpec spec file names displayed in stdout at the beginning of running tests in Regular Mode only when the log level is >= `warn`

- CHANGELOG.md
- lib/knapsack_pro/config/ci/github_actions.rb
- spec/knapsack_pro/config/ci/app_veyor_spec.rb
- spec/knapsack_pro/config/ci/buildkite_spec.rb
- spec/knapsack_pro/config/ci/circle_spec.rb
- spec/knapsack_pro/config/ci/cirrus_ci_spec.rb
- spec/knapsack_pro/config/ci/codefresh_spec.rb
- spec/knapsack_pro/config/ci/codeship_spec.rb
- spec/knapsack_pro/config/ci/github_actions_spec.rb
- spec/knapsack_pro/config/ci/gitlab_ci_spec.rb
- spec/knapsack_pro/config/ci/heroku_spec.rb
- spec/knapsack_pro/config/ci/semaphore2_spec.rb
- spec/knapsack_pro/config/ci/semaphore_spec.rb
- spec/knapsack_pro/config/ci/travis_spec.rb
* [`KNAPSACK_PRO_CI_NODE_RETRY_COUNT`](https://docs.knapsackpro.com/ruby/reference/#knapsack_pro_ci_node_retry_count)
> Add support for CI node retry count on GitHub Actions

- CHANGELOG.md
- lib/knapsack_pro/config/ci/app_veyor.rb
- lib/knapsack_pro/config/ci/base.rb
- lib/knapsack_pro/config/ci/buildkite.rb
- lib/knapsack_pro/config/ci/circle.rb
- lib/knapsack_pro/config/ci/cirrus_ci.rb
- lib/knapsack_pro/config/ci/codefresh.rb
- lib/knapsack_pro/config/ci/codeship.rb
- lib/knapsack_pro/config/ci/github_actions.rb
- lib/knapsack_pro/config/ci/gitlab_ci.rb
- lib/knapsack_pro/config/ci/heroku.rb
- lib/knapsack_pro/config/ci/semaphore.rb
- lib/knapsack_pro/config/ci/semaphore2.rb
- lib/knapsack_pro/config/ci/travis.rb
- lib/knapsack_pro/config/env.rb
- spec/knapsack_pro/config/env_spec.rb
Detect CI from environment and get the correct ENVs instead of trying all of them and risk conflicts.
Fixes https://trello.com/c/duyuldsW/76-detect-ci-first-before-reading-the-env-vars
> Detect CI from environment

- CHANGELOG.md
- lib/knapsack_pro/config/ci/app_veyor.rb
- lib/knapsack_pro/config/ci/base.rb
- lib/knapsack_pro/config/ci/buildkite.rb
- lib/knapsack_pro/config/ci/circle.rb
- lib/knapsack_pro/config/ci/cirrus_ci.rb
- lib/knapsack_pro/config/ci/codefresh.rb
- lib/knapsack_pro/config/ci/codeship.rb
- lib/knapsack_pro/config/ci/github_actions.rb
- lib/knapsack_pro/config/ci/gitlab_ci.rb
- lib/knapsack_pro/config/ci/heroku.rb
- lib/knapsack_pro/config/ci/semaphore.rb
- lib/knapsack_pro/config/ci/semaphore2.rb
- lib/knapsack_pro/config/ci/travis.rb
- lib/knapsack_pro/config/env.rb
- spec/knapsack_pro/config/env_spec.rb
Use `KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true` as the default value and ensure it's `true` for:
* GitHub Actions
* Buildkite
* Travis
* CodeShip
For other CI providers use `KNAPSACK_PRO_FIXED_QUEUE_SPLIT=false`:
* App Veyor
* Cirrurs CI
* CodeFresh
* GitLab CI
* Heroku CI
* Semaphore CI 1.0
* Semaphore CI 2.0
More info:
GitHub Actions, CodeShip use the same CI build ID for retried CI node. In such a case, Queue Mode would assume the queue is already consumed and there are no tests to run for retried CI node. You would expect to run the same set of tests as it was assigned to the CI node during the very first run. To achieve that, we use `KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true` then a retried CI node will run the same set of tests as on the very first run for a given (commit SHA, branch, and …
> Use `KNAPSACK_PRO_FIXED_QUEUE_SPLIT=true` as default value in Queue Mode and use `false` for proper CI providers

- CHANGELOG.md
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/repository_adapters/git_adapter.rb
- spec/knapsack_pro/config/env_spec.rb
Tested on:
- CircleCI
- Buildkite
- this worked also with the previous code
- Github Actions
- this **did not** work with the previous code
More info on the fix: https://stackoverflow.com/questions/73085141/git-shortlog-in-a-github-workflow-for-a-specific-directory
> Improve commit authors tracking

- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/knapsack_pro/runners/queue/rspec_runner_spec.rb
- spec/knapsack_pro/tracker_spec.rb
* fix(Queue Mode): ensure exit code is 1 when RSpec raised an exception
* Add missing spec for KnapsackPro::Tracker#unexecuted_test_files
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/214
> Handle RSpec exceptions when running RSpec in Queue mode (improvements)

- CHANGELOG.md
- lib/knapsack_pro/adapters/base_adapter.rb
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/base_allocator_builder.rb
- spec/knapsack_pro/adapters/base_adapter_spec.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/base_allocator_builder_spec.rb
Performance improvement: don't run `rake knapsack_pro:rspec_test_example_detector` when no slow test files are detected for RSpec. 
Thanks to that, we improve performance and save a few or a dozen seconds (depending on the project's complexity).
* https://github.com/KnapsackPro/knapsack_pro-ruby/issues/223
* https://github.com/KnapsackPro/knapsack_pro-ruby/issues/224
This PR change was tested with a [bin script](https://github.com/KnapsackPro/rails-app-with-knapsack_pro/blob/0e84152883167e4bb197ebc4c05bb9bde5e3b811/bin/knapsack_pro_queue_rspec_split_by_test_examples_unique_build#L5).
> Performance improvement: don't run `rake knapsack_pro:rspec_test_example_detector` when no slow test files are detected for RSpec

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/rspec_runner.rb
https://trello.com/c/0ZISAmYr
RSpec 3.10 has no method `rspec_is_quitting` and it fails when you use Queue Mode in the knapsack_pro gem.
RSpec 3.10 - the `rspec_is_quitting` method is missing: https://github.com/rspec/rspec-core/blob/v3.10.0/lib/rspec/core/world.rb
RSpec 3.12 - [has the method](https://github.com/rspec/rspec-core/blob/1eeadce5aa7137ead054783c31ff35cbfe9d07cc/lib/rspec/core/world.rb#L18)
Call the `rspec_is_quitting` method only if it exists on RSpec World object.
> fix(RSpec): allow to use Queue Mode for RSpec <= 3.10 when the `rspec_is_quitting` method is not present for RSpec World object

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/formatters/time_tracker.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/formatters/time_tracker_specs.rb
Turnip specs have a different naming format than RSpec's: `foo.feature` vs `foo_spec.rb`.
This PR makes sure `.feature` files are recorded.
Also, it stops recording `UNKNOWN_PATH` that would generate an error in case of a CI node retry (see below for details).
- In rails-app-with-knapsack-pro
- `git commit --allow-empty -m wip`
- `bin/knapsack_pro_queue_turnip 0 2 20231207-01`
- `bin/knapsack_pro_queue_turnip 0 2 20231207-01`
You should get:
```
D, [2023-12-07T14:08:19.969425 #14329] DEBUG -- : [knapsack_pro] POST http://api.knapsackpro.test:3000/v1/queues/queue
D, [2023-12-07T14:08:19.969501 #14329] DEBUG -- : [knapsack_pro] API request UUID: 668869b5-a70d-4261-a624-3f47e31d9971
D, [2023-12-07T14:08:19.969553 #14329] DEBUG -- : [knapsack_pro] API response:
D, [2023-12-07T14:08:19.969650 …
```
> Fix Turnip and UNKNOWN_PATH error

- .circleci/config.yml
- README.md
- lib/knapsack_pro/formatters/time_tracker_fetcher.rb
- spec/spec_helper.rb
This PR takes care of the following:
- use CircleCI configuration v2.1
- (besides the gem tests) run integration tests by cloning rails-app-with-knapsack-pro
- remove the CodeClimate ENV because we are not using it
- make sure Rubocop exits with an error if there's an offense (and fix a small offense)
This setup catches:
- #231 (https://app.circleci.com/pipelines/github/KnapsackPro/knapsack_pro-ruby/1055/workflows/3dd23caf-13d7-4683-b11e-dd5aacf969cf/jobs/2421, https://app.circleci.com/pipelines/github/KnapsackPro/knapsack_pro-ruby/1055/workflows/3dd23caf-13d7-4683-b11e-dd5aacf969cf/jobs/2429)
- #233 (https://app.circleci.com/pipelines/github/KnapsackPro/knapsack_pro-ruby/1059/workflows/b46cd967-adad-4615-9837-ae932f1ff703)
See the builds for this branch on …
> integration tests

- .circleci/config.yml
- CHANGELOG.md
- lib/knapsack_pro/runners/queue/minitest_runner.rb
Rails in `test/test_helper.rb` includes:
```
require 'rails/test_help'
```
that contains:
```
require "active_support/testing/autorun"
```
which calls [`Minitest.autorun`](https://github.com/minitest/minitest/blob/43d4efc936ee760dbe2c797adc431c17a3b4afc2/lib/minitest.rb#L67), which, in turn, installs an `at_exit` that will run Minitest tests.
This is useful when you [don't want to call `Minitest.run`](https://blog.arkency.com/2013/06/are-we-abusing-at-exit/) explicitly. But we actually do so in the Knapsack Pro runner.
We forgot to add the `class_variable_set` as part of https://github.com/KnapsackPro/knapsack_pro-ruby/commit/6849d1fd2610d2d7469ae2a7148ab8ef5faab4c7 (make sure to read the link to the Minitest issue in the commit body).
**This change is not needed in Regular Mode because …
> Minitest: avoid installing `at_exit`

- README.md
N/A
N/A
This PR makes the readme part about publishing the gem a bit less ambiguous.
N/A
~~- [ ] You follow the architecture outlined below for RSpec in Queue Mode, which is a work in progress (feel free to propose changes):~~
~~- Pure: `lib/knapsack_pro/pure/queue/rspec_pure.rb` contains pure functions that are unit tested.~~
~~- Extension: `lib/knapsack_pro/extensions/rspec_extension.rb` encapsulates calls to RSpec internals and is integration and e2e tested.~~
~~- Runner: `lib/knapsack_pro/runners/queue/rspec_runner.rb` invokes the pure code and the extension to produce side effects, which are integration and e2e tested.~~
> Update publishing readme

- spec/integration/runners/queue/rspec_runner.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/237
I forgot to apply suggestions to integration tests from a code review to [the PR](https://github.com/KnapsackPro/knapsack_pro-ruby/pull/237). This PR fixes that.
* use stub word instead of mock
> refactor(integration tests): use stub instead of mock wording

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
- lib/knapsack_pro/pure/queue/rspec_pure.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
- spec/knapsack_pro/pure/queue/rspec_pure_spec.rb
https://trello.com/c/iyN1GKYS/320-bug-rspec-knapsackpro-700-fails-with-the-dotenv-gem
https://github.com/KnapsackPro/knapsack_pro-ruby/issues/242
Version 7.0.0 introduced some fundamental changes, namely fetching, loading and running batches of specs **after** executing suite hooks, so that such hooks are only ran once, not before every batch. As a result, if `rails_helper` is only required in spec files, which is the RSpec default, instead of e.g. in `.rspec`, then some `before(:suite)` hooks, e.g. defined by gems, are registered after suite hooks had already been executed by the test suite. In comparison, RSpec loads all the spec files **before** executing `before(:suite)` hooks.
This PR conditionally adds `--require rails_helper` to cli arguments of …
> Require rails_helper before configuring RSpec

- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
Currently when unexpected error raised, we only get the class name from `exception.inspect`, this PR adds details to the logger to be able to trace or debug the cause.
Add more logs when unexpected error raised in runner process.
> [RSpec] [Queue Mode] Log error message and backtrace when unexpected failure raised in process

- CHANGELOG.md
- lib/knapsack_pro/client/connection.rb
- spec/spec_helper.rb
Ticket https://trello.com/c/nInb3gxY/359-knapsackpro-gem-dx-remove-manual-steps-for-webmock-vcr
Currently, setting up Knapsack Pro with WebMock/VCR [requires additional steps](https://docs.knapsackpro.com/knapsack_pro-ruby/guide/?rails=yes&vcr=yes#vcrwebmock) because WebMock replaces `Net::HTTP` with its own client that (also) blocks requests to the Knapsack Pro API.
Some codebases configure WM in a way that doesn't play well with Knapsack Pro, even when the manual configuration steps are followed.
For example, each call to `WebMock.disable_net_connect!` without passing `allow: ['api.knapsackpro.com']` overrides the previous `WebMock.disable_net_connect!(allow: ['api.knapsackpro.com'])` call preventing requests to `api.knapsackpro.com`.
Users could have multiple calls to `WebMock` that …
> Remove manual steps to configure WebMock (and VCR)

- CHANGELOG.md
- lib/knapsack_pro/config/env.rb
- spec/knapsack_pro/config/env_spec.rb
https://trello.com/c/VMKgyjFP/365-warn-when-overriding-envs-in-supported-ci-ruby-js
~~TODO: links to related PRs or issues~~
Log when `KNAPSACK_PRO_*` environment variables are set manually if their values could be automatically determined from supported CI environments, and both values are different.
Uses `logger.info` to display a message when both the `KNAPSACK_PRO_*` and CI envs are present and different from each other.
- Runner: `lib/knapsack_pro/runners/queue/rspec_runner.rb` invokes the pure code and the extension to produce side effects, which are …
> Warn when CI env variables are overwritten

- CHANGELOG.md
update(changelog): add breaking change info for 6.0.4 version for simplecov and Minitest in Queue Mode users
* https://github.com/KnapsackPro/knapsack_pro-ruby/issues/257
> update(changelog): add breaking change info for 6.0.4 version for simplecov and Minitest in Queue Mode users

- CHANGELOG.md
- lib/tasks/queue/cucumber.rake
- lib/tasks/queue/minitest.rake
- lib/tasks/queue/rspec.rake
[Ticket](https://trello.com/c/sZx3WBZ0/391-improve-terminal-ux-for-the-gem-use-kernelexec-instead-of-kernelsystem-when-starting-queue-mode-in-ruby-to-use-a-single-ruby-pro)
[`#system`](https://rubydoc.info/stdlib/core/Kernel#system-instance_method) executes the passed command into a subshell. It pretty much executes fork, exec, and wait.
[`#exec`](https://rubydoc.info/stdlib/core/Kernel#exec-instance_method) replaces the current process avoiding a fork/wait.
Also, using `exec` delegates the exit/error handling to the replacing process making the code introduced in https://github.com/KnapsackPro/knapsack_pro-ruby/commit/7862c5e6 unneeded:
```ruby
exitstatus = $?.exitstatus
if exitstatus.nil?
puts 'Something went wrong. Most likely, the process has been killed. Knapsack Pro has been …
```
> Avoid unnecessary process in queue mode

- CHANGELOG.md
- knapsack_pro.gemspec
- lib/knapsack_pro/formatters/time_tracker.rb
- lib/knapsack_pro/tracker.rb
- lib/knapsack_pro/utils.rb
- spec/knapsack_pro/utils_spec.rb
[link to the internal story](https://trello.com/c/EVsS01sV)
Changes introduced by Timecop 0.9.9:
Process.clock_gettime is mocked.
* https://github.com/travisjeffery/timecop/pull/419
Timecop 0.9.10 makes `Process.clock_gettime` optionally mocked. The default is `Timecop.mock_process_clock = false`.
* https://github.com/travisjeffery/timecop/pull/427
Our old PRs related to time tracking and mocking time:
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/132
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/38
Add support for Timecop 0.9.9 so that we could track proper tests' execution time when `Process.clock_gettime` is mocked.
* Knapsack Pro ignores the `Process.clock_gettime` mocked by the Timecop gem.
- Pure: `lib/knapsack_pro/pure/queue/rspec_pure.rb` contains pure …
> fix(timecop gem): add support for Timecop 0.9.9 so that we  could track proper tests' execution time when `Process.clock_gettime` is mocked

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/base_runner.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
https://trello.com/c/oQCHRpec
https://docs.knapsackpro.com/ruby/troubleshooting/#why-does-the-ci-node-hang-backtrace-debugging
Log threads when the OS signal is received to simplify debugging, especially when a CI node hangs.
> Log threads when the OS signal is received to simplify debugging, especially when a CI node hangs.

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/base_runner.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/266
* Add link to how to read the backtrace:
https://knapsackpro.com/perma/ruby/backtrace-debugging
* fix a flaky test
TODO: changes introduced by this PR
> Add a link to help you read the backtrace

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/base_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- **Story**: https://trello.com/c/fRBnccqI/486-bugknapsackpro-gem-fix-an-error-when-a-backtrace-is-nil-in-log-threads
- **Issue**: https://github.com/KnapsackPro/knapsack_pro-ruby/issues/270
`#backtrace` could be `nil` in:
- [Exception](https://github.com/ruby/ruby/blob/638b4468b8826a34d7e513b56153ef4363d5bcf4/error.c#L1838)
- [Thread](https://github.com/ruby/ruby/blob/dd4677cf0654a7512df0809a31f5eac6bce5b97d/thread.c#L5339)
Better to look at the c source as the docs may not be always clear on what the return values are (as in this case).
I don't think we need additional test coverage because we are not dealing with a bug that could cause a regression.
- Extension: …
> fix: handle nil backtrace

- CHANGELOG.md
- lib/knapsack_pro/runners/queue/base_runner.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
TODO:  N/A
* https://github.com/KnapsackPro/knapsack_pro-ruby/issues/270#issuecomment-2401539528
Set `RSpec.world.wants_to_quit` to true when any signal is received by the knapsack_pro gem. This allows RSpec to gracefully exit as soon as the signal is received, instead of waiting for the test file to finish running.
This also ensures that external libraries, like datadog-ci, behave properly when RSpec is quitting.
- Runner: `lib/knapsack_pro/runners/queue/rspec_runner.rb` invokes the pure code and the extension to produce side effects, which are integration …
> Set `RSpec.world.wants_to_quit` to true when any signal is received by the knapsack_pro gem to allow graceful exit 

- CHANGELOG.md
- lib/knapsack_pro/test_case_detectors/rspec_test_example_detector.rb
- spec/knapsack_pro/test_case_detectors/rspec_test_example_detector_spec.rb
RSpec split by examples feature: https://docs.knapsackpro.com/ruby/split-by-test-examples/
Issue:
* https://github.com/KnapsackPro/knapsack_pro-ruby/issues/274
When an error occurs while loading slow test files, the RSpec JSON report contains errors mixed with ANSI codes. By default, RSpec produces colored output.
We use the `--no-color` option to remove the ANSI codes and make the error message more readable.
- Runner: `lib/knapsack_pro/runners/queue/rspec_runner.rb` invokes the pure code and the extension to produce side effects, which are integration and …
> A more readable error message for the RSpec split by examples JSON report (remove ANSI codes that are not human-readable)

- spec/integration/runners/queue/rspec_runner_spec.rb
TODO: [link to the internal story](https://trello.com/c/cAGLlpjL)
* fix(specs): require ostruct explicitly to make the spec work in Ruby 3.4
> fix(specs): require ostruct explicitly to make the spec work in Ruby 3.4

- spec/integration/runners/queue/rspec_runner_spec.rb
TODO: [link to the internal story](https://trello.com/c/cAGLlpjL)
Make the test suite pass on Ruby 3.4.0-preview2 and keep tests passing on older Ruby versions too.
Tested locally. There is no `cimg/ruby:3.4` docker image available to test on CI yet.
> Make the test suite pass on Ruby 3.4.0-preview2 and keep tests passing on older Ruby versions too.

- knapsack_pro.gemspec
TODO: [link to the internal story](https://trello.com/c/cAGLlpjL)
* https://github.com/KnapsackPro/rails-app-with-knapsack_pro/pull/70
Add ostruct to the list of gems in development environment to ensure it works with Ruby 3.5 and to get rid of the warning in Ruby 3.4
> Add ostruct to the list of gems in development environment to ensure it works with Ruby 3.5 and to get rid of the warning in Ruby 3.4

- CHANGELOG.md
- lib/knapsack_pro/test_case_mergers/rspec_merger.rb
- spec/knapsack_pro/test_case_mergers/rspec_merger_spec.rb
TODO: [link to the internal story](https://trello.com/c/f8uD3QC0)
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/277
About the problem:
We add up a spec file execution time and all test example execution times to determine the time of a test file, which doubles the execution time of a spec in the worst-case scenario. This leads to some tests not being split by test examples and unbalanced builds.
Use whichever execution time is larger:
* The execution time of the entire test file
* The sum of execution times of the test file examples
- Runner: …
>  fix(RSpec split by examples): Properly determine slow test files when test example execution times and full test file execution time are both known

- .circleci/config.yml
- CHANGELOG.md
- lib/knapsack_pro/base_allocator_builder.rb
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/slow_test_file_determiner.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
- spec/knapsack_pro/base_allocator_builder_spec.rb
- spec/knapsack_pro/config/env_spec.rb
- spec/knapsack_pro/slow_test_file_determiner_spec.rb
TODO: [link to the internal story](https://trello.com/c/f8uD3QC0)
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/281
Relate to the RSpec split by examples feature:
https://docs.knapsackpro.com/ruby/split-by-test-examples/
If a user skips some test files, for example, using the RSpec `--tag` option, then RSpec might still load a file but not run it or only run some of the test examples from it.
If a lot of test files are skipped, then the actual average CI node execution time would be much smaller than the estimated time (Knapsack Pro does not know how many test files are filtered out by `--tag`).  This can lead to not determining enough test files as slow, which examples should split. As a result, CI build is unbalanced.
To solve that problem, we added a new environment variable …
> Add `KNAPSACK_PRO_SLOW_TEST_FILE_THRESHOLD` to improve the RSpec split by examples feature with many skipped tests 

- .circleci/config.yml
- CHANGELOG.md
- lib/knapsack_pro/base_allocator_builder.rb
- lib/knapsack_pro/config/env.rb
- spec/knapsack_pro/base_allocator_builder_spec.rb
- spec/knapsack_pro/config/env_spec.rb
Fix for a bug introduced in the following PR when you run tests on a single CI node and use `KNAPSACK_PRO_RSPEC_SPLIT_BY_TEST_EXAMPLES=true`.
* https://github.com/KnapsackPro/knapsack_pro-ruby/pull/282
```
vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.12.0/lib/knapsack_pro/slow_test_file_determiner.rb:29:in `read_from_json_report'
/home/betterment/for_business/impersonate/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.12.0/lib/knapsack_pro/adapters/base_adapter.rb:30:in `slow_test_file?'
/home/betterment/for_business/impersonate/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.12.0/lib/knapsack_pro/formatters/time_tracker.rb:123:in `rspec_split_by_test_example?'
/home/betterment/for_business/impersonate/vendor/bundle/ruby/3.2.0/gems/knapsack_pro-7.12.0/lib/knapsack_pro/formatters/time_tracker.rb: …
```
> fix(RSpec split by examples): properly disable split by test examples on a single node to speed up tests

- CHANGELOG.md
- lib/knapsack_pro/allocator.rb
- lib/knapsack_pro/config/env.rb
- lib/knapsack_pro/queue_allocator.rb
- lib/knapsack_pro/runners/queue/cucumber_runner.rb
- lib/knapsack_pro/runners/queue/minitest_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/integration/runners/fallback_spec.rb
- spec/integration/runners/queue/cucumber_runner_fallback_spec.rb
- spec/integration/runners/queue/minitest_runner_fallback_spec.rb
- spec/integration/runners/queue/rspec_runner_fallback_spec.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
- spec/knapsack_pro/allocator_spec.rb
- spec/knapsack_pro/config/env_spec.rb
- spec/knapsack_pro/queue_allocator_spec.rb
- spec/knapsack_pro/runners/rspec_runner_spec.rb
https://trello.com/c/GCRO05YP/513-custom-exit-code-when-cannot-connect-to-the-api-and-fallback-mode-is-disabled
Allow users to set a custom error exit code (`KNAPSACK_PRO_FALLBACK_MODE_ERROR_EXIT_CODE`) whenever Knapsack Pro fails because Fallback Mode cannot be used.
Since we are catching the error, we don't print the backtraces anymore. This is a plus as you'd expect those only in case of an unhandled error. See below for the actual differences.
- Runner: `lib/knapsack_pro/runners/queue/rspec_runner.rb` invokes the pure code and the extension to produce side …
> Custom exit code for fallback mode error

- CHANGELOG.md
- lib/knapsack_pro/extensions/rspec_extension.rb
- lib/knapsack_pro/runners/queue/base_runner.rb
- lib/knapsack_pro/runners/queue/rspec_runner.rb
- spec/integration/runners/queue/rspec_runner_spec.rb
https://trello.com/c/xvarNSRi
Issue:
* https://github.com/KnapsackPro/knapsack_pro-ruby/issues/285
Related PR:
* https://github.com/KnapsackPro/docs.knapsackpro.com/pull/229
Improve debugging for hanging CI node. 
* Show hanging spec files in the RSpec output.
* Show a command to reproduce the current batch of tests. It includes seed if the RSpec tests were running in random order.
> Improve debugging for hanging CI node. Show hanging spec files in the RSpec output and a command to reproduce the current batch of tests 

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
- spec/knapsack_pro/adapters/rspec_adapter_spec.rb
https://trello.com/c/RnkCLz1f/83-update-the-idpath-in-rspec-to-detect-turnips-id-paths
Result:
- https://staging.knapsackpro.com/dashboard/organizations/1/projects/55/test_suites/124/builds/0d9d5db2-7238-4dcc-99be-86d6ea877265#tab-test-files
- https://app.circleci.com/pipelines/github/KnapsackPro/knapsack_pro-ruby/1709/workflows/da07c790-6194-4fdc-b6c8-02afcc7b3974/jobs/28293
> Detect Turnip id paths

- CHANGELOG.md
- lib/knapsack_pro/adapters/rspec_adapter.rb
In the [RSpec code](https://github.com/rspec/rspec/blob/86b5e4218eece4c1913fe9aad24c0a96d8bc9f40/rspec-core/lib/rspec/core/example.rb#L122), the regex is different than the one in the Rubular link.
Let's use the regex from the source code for both cases.
> RSpec: Use the same regex

- CHANGELOG.md
- lib/knapsack_pro/config/ci/semaphore2.rb
- spec/knapsack_pro/config/ci/semaphore2_spec.rb
https://trello.com/c/ov3beE5i/657-fix-commit-hash-branch-name-and-user-seat-detection-for-semaphore
> Semaphore: Fix branch name and user seat detection

- .circleci/config.yml
- CHANGELOG.md
- lib/tasks/queue/minitest.rake
- lib/tasks/queue/rspec.rake
https://trello.com/c/Y4wzIYVr
We want Knapsack Pro not to modify the behaviour of the underlying test runner, so that users don't have to modify their test to use Knapsack Pro.
When people run RSpec (`bin/rspec` or `bundle exec rspec`), Minitest (`bin/rails test` or `ruby -Ilib:test test/my_test.rb`), or Cucumber (`bin/cucumber` or `bundle exec cucumber`), to test rake tasks, they have to do something like `Rake.application.rake_require("tasks/my_task")`, `Rake.load_rakefile("tasks/my_task.rake")`, or `Rails.application.load_tasks`.
In Queue Mode, Knapsack Pro, given how it's run, loads tasks for RSpec and Minitest, so we have to clear them. In the long term, we should review the invocation chain so that we don't load tasks just to remove them.
Notice that Cucumber shells out with a …
> Do not load Rake tasks on behalf of the user for RSpec and Minitest in Queue Mode

- CHANGELOG.md
- knapsack_pro.gemspec
- spec/fixtures/vcr_cassettes/api/v1/build_distributions/subset/invalid_test_suite_token.yml
- spec/fixtures/vcr_cassettes/api/v1/build_distributions/subset/success.yml
- spec/fixtures/vcr_cassettes/api/v1/build_subsets/create/invalid_test_suite_token.yml
- spec/fixtures/vcr_cassettes/api/v1/build_subsets/create/success.yml
- spec/integration/api/build_distributions_subset_spec.rb
- spec/integration/api/build_subsets_create_spec.rb
- spec/knapsack_pro/config/ci/app_veyor_spec.rb
- spec/knapsack_pro/config/ci/cirrus_ci_spec.rb
- spec/knapsack_pro/config/ci/codeship_spec.rb
- spec/knapsack_pro/config/ci/heroku_spec.rb
- spec/knapsack_pro/config/ci/semaphore2_spec.rb
- spec/knapsack_pro/config/ci/semaphore_spec.rb
- spec/knapsack_pro/config/ci/travis_spec.rb
- spec/knapsack_pro/config/env_spec.rb
- spec/knapsack_pro/repository_adapters/git_adapter_spec.rb
> Use main instead of master

- CHANGELOG.md
- lib/knapsack_pro/formatters/time_tracker.rb
- spec/knapsack_pro/formatters/time_tracker_specs.rb
https://trello.com/c/zrjMajhs/758-support-fix-time-tracker
The time tracker missed some `before(:all)/after(:all)` that weren't in the top level group.
With this change, the following `X` gaps are considered `before(:all)/after(:all)`:
```ruby
describe do
X (example_started)
it {}
X (example_group_started)
describe do
X (example_started)
it {}
X (example_group_finished)
end
X (example_group_started)
describe do
X (example_started)
it {}
end
X (example_group_finished)
end
```
- Runner: `lib/knapsack_pro/runners/queue/rspec_runner.rb` invokes the pure code and …
> [RSpec] Fix issues in TimeTracker

- CHANGELOG.md
- lib/knapsack_pro/formatters/time_tracker.rb
The `Hash#sum` method yields an unpredictable result when extracting key and value pairs from a `Hash`. Use `Hash#reduce` to get consistent results.
```ruby
time_all_by_group_id_path = {
"packs/a_spec.rb[1]" => 0.4432561059966247,
"packs/a_spec.rb[1:5]" => 0.001432769997336436,
"packs/a_spec.rb[1:6]" => 0.00025801000083447434,
"packs/a_spec.rb[1:6:1]" => 0.00034806999974534847,
"packs/a_spec.rb[1:6:2]" => 0.00036408000050869305,
"packs/a_spec.rb[1:6:3]" => 0.0003385700001672376
}
```
Code that iterates over the Hash.
```ruby
example[:path] = "packs/a_spec.rb[1]"
time_all_by_group_id_path.sum do |group_id_path, time|
puts "group_id_path: #{group_id_path.inspect}"
puts "time: #{time.inspect}"
puts
next time if group_id_path.start_with?(example[:path])
next time if …
```
> Fix a Hash#sum bug in the time tracker for RSpec
